pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh '''
                   echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL} ${env.CURRENT_BRANCH} ${env.CURRENT_VERSION}"
                '''
                sh 'ls -l'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
